export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";

export const FEEDBACK_REQUEST = "FEEDBACK_REQUEST";
export const FEEDBACK_SUCCESS = "FEEDBACK_SUCCESS";
export const FEEDBACK_FAIL = "FEEDBACK_FAIL";

export const CHANGE_ORDERSTATUS_REQUEST = "CHANGE_ORDERSTATUS_REQUEST";
export const CHANGE_ORDERSTATUS_SUCCESS = "CHANGE_ORDERSTATUS_SUCCESS";
export const CHANGE_ORDERSTATUS_FAIL = "CHANGE_ORDERSTATUS_FAIL";
